language: php

php:
  - 7.2

services:
  - postgresql

addons:
  postgresql: "9.6"

before_install: cd www

cache:
  directories:
    - node_modules
    - vendor

install:
  - cp .env.travis-ci .env
  - psql -c 'create database travis_ci_test;' -U postgres
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan migrate
  - composer dump-autoload
  - php artisan db:seed
  - php artisan config:clear
  - php artisan key:generate

script:
  - vendor/bin/phpunit