language: php

php:
  - 7.1
  - 7.2

addons:
  chrome: stable

install:
  - cp www/.env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - cd www/ & php artisan serve &

script:
  - cd www/ & php artisan dusk